version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: test
          command: yarn test
      - run:
          name: build-chrome
          command: NODE_ENV=production yarn run build-prod
